### ISSUE TITLE
Pawn CML to Genesis Bank page

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#123]
![image](https://user-images.githubusercontent.com/12605218/127759259-d5856e55-c813-40ae-a9eb-388d35db20c9.png)

**Comment by kevingzhang** [comment]
let @geopor review the text

**Comment by lxm218** [comment]
suggest to use pawn loan agreement as a reference. Need to consider prepayment terms.

**Comment by kevingzhang** [comment]
After few hours, the next update will have the new const value as describe below:
Every 1000 blocks (about 100 minutes) a billing cycle. 
Every billing cycle the interest rate is 0.08%. 
The loan term is 200,000 blocks, about 55 hours. 

User need to repay the loan before the 200,000 term ends, otherwise in default.

The user can repay any time. The blockheight when reply - the blockheight loan starts is the actually loan term. The actual loan term / Billing cycle is how many times the interest rate applies. When the repay time full between 2 and 3 billing cycle, we take 3. always the ceiling number. We calculate the total interest using the ceiling of billing cycles * interest_rate * loan_amount.
the current loan_amount is 500T regardless type of seed.

When user repay the primary + interest, the collateral seed will be redeemed to the user.Both the primary and interest TEA token will be burned.

Please write the rule into formal English and put somewhere on the UI or link

**Comment by geopor** [comment]
What does it mean for a loan to be in default? Can they still repay with a penalty, or is their collateral liquidated?

**Comment by geopor** [comment]
Pawn is the wrong metaphoric language for our loan offer.

Pawn means to put something valuable from your house up for collateral. It also implies the person is desperate. It doesn't apply for TEA Project loans because we have a formal collateral system (only can use CML). Also, to pawn something has no general meaning - it is only relevant if you actually go to the pawn store. No one in crypto or banking uses the pawn metaphor because it doesn't have an abstractable generalized meaning. 

Pawn stores are also considered predatory lenders so we don't want to be associated with that industry.

####
Updated rules in next comment.

**Comment by geopor** [comment]
## Deposit CML to use as collateral for a TEA token loan.

- Each billing cycle is 1000 blocks long (approximately 100 minutes).
- The interest rate for every billing cycle is 0.08%.
- The loan term is 200,000 blocks, approximately 55 hours.
- The current loan amount is 500T regardless of the type of seed used for collateral.

**Loan Repayment**
The borrower needs to repay the loan before the 200,000 block-term ends. If the full borrowed amount is not repaid by the end of the loan term, the loan is considered to be in default.

The borrower can repay the loan at any time. If repaid before the end of the loan term, the adjusted loan term is equal to **blockheight when repaid** - **blockheight at loan start**. The adjusted loan term/billing cycle calculates the number of times the interest rate is applied. This number is always rounded up. The total interest on the loan is calculated as **rounded number of billing cycles** * **interest rate** * **loan amount**. The interest rate is 0.08%, and the loan amount from the Genesis bank is always 500T.

**Return of Collateral**
When the borrower has repaid the loaned amount + interest, their collateral CML seed will be returned to them. Both the primary loan amount and interest in TEA token that's been repaid will be burned.

**Comment by kevingzhang** [comment]
> What does it mean for a loan to be in default? Can they still repay with a penalty, or is their collateral liquidated?

No. The seed will be burn and there is no way to repay as long as in default

**Comment by kevingzhang** [comment]
> Pawn is the wrong metaphoric language for our loan offer.
> 
> Pawn means to put something valuable from your house up for collateral. It also implies the person is desperate. It doesn't apply for TEA Project loans because we have a formal collateral system (only can use CML). Also, to pawn something has no general meaning - it is only relevant if you actually go to the pawn store. No one in crypto or banking uses the pawn metaphor because it doesn't have an abstractable generalized meaning.
> 
> Pawn stores are also considered predatory lenders so we don't want to be associated with that industry.
> 
> Updated rules in next comment.

I do not use the word pawn either

**Comment by geopor** [comment]
> > What does it mean for a loan to be in default? Can they still repay with a penalty, or is their collateral liquidated?
> 
> No. The seed will be burn and there is no way to repay as long as in default

Ok updated text to say that CML will be liquidated.

**Comment by kevingzhang** [comment]
please push this issue forward @lxm218

**Comment by lxm218** [comment]
see #132
