### ISSUE TITLE
Wallet welcome page update to allow registrations

### ISSUE THREAD

**Issue by geopor** [tearust/tea-browser-wallet#235]
The wallet welcome page needs an update to allow contestants to register: https://wallet.teaproject.org/#/home

## Required fields:
- Email
- Your account address copied from your polkadot browser extension.
- Binance Smart Chain or ERC20  address (rewards will be paid out using Binance Smart Chain)

## Optional:
- Referrer 

Note that you don't need to fill out this form if you've already signed up for the current epoch using the Google form. This sign-up is for those joining while the epoch is in progress.

**Comment by kevingzhang** [comment]
@geopor do you think you should add some text telling users that if they have registered already, there is no need for them to refill this. 

This is only used for people not registered but would like to join the contest in the middle.

**Comment by kevingzhang** [comment]
@geopor After a technical discussion, I found out this is not technically doable.
When new user see the welcome page, he has no account yet. of course, he has no balance in his account. After click the enroll button he need to pay for a tx fee. of course, he cannot pay. so this tx won't get through.

I think we may have to give up this idea. Just let the new user go to the existing registration form. and you can manually add them to the leader board every day. 

They do not have to wait till showing in the leader board to start contesting. You probably need to explain this somewhere, so that the new user will know they can start mining immediately without seeing his account listed in the leader board.

**Comment by geopor** [comment]
Ok then the existing Google form will be used throughout the contest. Since they will not be added automatically, Google form will notify me of new sign ups and I'll add them manually.

Also added following text to form:
> • If you're signing up after the contest starts, keep an eye on your email for registration confirmation. You will not be able to login to wallet.teaproject.org until you're added to the contestants roll which could take some hours.
